name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - run: sudo apt-get update && sudo apt-get install -y libsdl3-dev

      - run: make
